#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMAddressVerifySyntaxOnlyResponse
@end

@interface CMAddressVerifySyntaxOnlyResponse : CMObject

/* True if the email address is syntactically valid, false if it is not [optional]
 */
@property(nonatomic) NSNumber* validAddress;
/* Domain name of the email address [optional]
 */
@property(nonatomic) NSString* domain;
/* True if the email domain name is a free provider (typically a free to sign up web email provider for consumers / personal use), false otherwise. [optional]
 */
@property(nonatomic) NSNumber* isFreeEmailProvider;
/* True if the email address is a disposable email address, false otherwise; these disposable providers are not typically used to receive email and so will have a low likelihood of opening mail sent there. [optional]
 */
@property(nonatomic) NSNumber* isDisposable;

@end
