#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDateTimeStandardizedParseResponse
@end

@interface CMDateTimeStandardizedParseResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Result of performing a date time parsing [optional]
 */
@property(nonatomic) NSDate* parsedDateResult;
/* Year of the parsed date time result [optional]
 */
@property(nonatomic) NSNumber* year;
/* Month of the parsed date time result [optional]
 */
@property(nonatomic) NSNumber* month;
/* Day of the parsed date time result [optional]
 */
@property(nonatomic) NSNumber* day;
/* Hour of the parsed date time result (24-hour) [optional]
 */
@property(nonatomic) NSNumber* hour;
/* Minute of the parsed date time result [optional]
 */
@property(nonatomic) NSNumber* minute;
/* Second of the parsed date time result [optional]
 */
@property(nonatomic) NSNumber* second;
/* Day of week [optional]
 */
@property(nonatomic) NSString* dayOfWeek;

@end
