#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMGetPublicHolidaysRequest
@end

@interface CMGetPublicHolidaysRequest : CMObject

/* Two-letter code (FIPS 10-4 or ISO 3166-1) of the country; if not specified, defaults to United States [optional]
 */
@property(nonatomic) NSString* rawCountryInput;
/* Optional - the year in which to retrieve the holidays; if left blank (0) it will default to the current year [optional]
 */
@property(nonatomic) NSNumber* year;

@end
