#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMGeolocateStreetAddressResponse
@end

@interface CMGeolocateStreetAddressResponse : CMObject

/* Two-letter country code of IP address [optional]
 */
@property(nonatomic) NSString* countryCode;
/* Country name of IP address [optional]
 */
@property(nonatomic) NSString* countryName;
/* Street address of IP address [optional]
 */
@property(nonatomic) NSString* streetAddress;
/* City of IP address [optional]
 */
@property(nonatomic) NSString* city;
/* State/region of IP address [optional]
 */
@property(nonatomic) NSString* regionName;
/* Zip or postal code of IP address [optional]
 */
@property(nonatomic) NSString* zipCode;

@end
