#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMTimezone.h"
@protocol CMTimezone;
@class CMTimezone;



@protocol CMGetTimezonesResponse
@end

@interface CMGetTimezonesResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Full name of the country [optional]
 */
@property(nonatomic) NSString* countryFullName;
/* Two-letter ISO 3166-1 country code [optional]
 */
@property(nonatomic) NSString* iSOTwoLetterCode;
/* Two-letter FIPS 10-4 country code [optional]
 */
@property(nonatomic) NSString* fIPSTwoLetterCode;
/* Three-letter ISO 3166-1 country code [optional]
 */
@property(nonatomic) NSString* threeLetterCode;
/* Time zones (IANA/Olsen) in the country [optional]
 */
@property(nonatomic) NSArray<CMTimezone>* timezones;

@end
