#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMIPThreatResponse
@end

@interface CMIPThreatResponse : CMObject

/* True if the input IP address is a threat, false otherwise [optional]
 */
@property(nonatomic) NSNumber* isThreat;
/* Specifies the type of IP threat; possible values include Blocklist, Botnet, WebBot [optional]
 */
@property(nonatomic) NSString* threatType;

@end
