#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMGeolocateResponse.h"
@protocol CMGeolocateResponse;
@class CMGeolocateResponse;



@protocol CMIPIntelligenceResponse
@end

@interface CMIPIntelligenceResponse : CMObject

/* True if the IP address is a known bot, otherwise false [optional]
 */
@property(nonatomic) NSNumber* isBot;
/* True if the IP address is a known Tor exit node, otherwise false [optional]
 */
@property(nonatomic) NSNumber* isTorNode;
/* True if the IP address is a known threat IP, otherwise false [optional]
 */
@property(nonatomic) NSNumber* isThreat;
/* True if the IP address is in the European Union, otherwise false [optional]
 */
@property(nonatomic) NSNumber* isEU;
/* Returns the location of the IP address [optional]
 */
@property(nonatomic) CMGeolocateResponse* location;
/* ISO 4217 currency code for the IP address location [optional]
 */
@property(nonatomic) NSString* currencyCode;
/* Name of the currency in English [optional]
 */
@property(nonatomic) NSString* currencyName;
/* Region (continent) in which the country is located; possible values are None, Europe, Americas, Asia, Africa, Oceania [optional]
 */
@property(nonatomic) NSString* regionArea;
/* Subregion in which the country is located; possible values are None, NorthernEurope, WesternEurope, SouthernEurope, EasternEurope, CentralAmerica, NorthernAmerica, SouthAmerica, EasternAfrica, MiddleAfrica, NorthernAfrica , SouthernAfrica , WesternAfrica , CentralAsia , EasternAsia , SouthernAsia , SouthEasternAsia , WesternAsia , Southern , Middle , AustraliaandNewZealand , Melanesia , Polynesia , Micronesia , Caribbean, [optional]
 */
@property(nonatomic) NSString* subregionArea;

@end
