#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMLeadEnrichmentResponse
@end

@interface CMLeadEnrichmentResponse : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* The type of the lead; possible types are Junk (a single individual using a disposable/throwaway email address); Individual (a single individual, typically a consumer, not purchasing on behalf of a business); SmallBusiness (a small business, typically with fewer than 100 employees); MediumBusiness (a medium business, larger than 100 employees but fewer than 1000 employees); Enterprise (a large business with greater than 1000 employees); Business (a business customer of unknown size) [optional]
 */
@property(nonatomic) NSString* leadType;
/* The person's business email address for the lead [optional]
 */
@property(nonatomic) NSString* contactBusinessEmail;
/* The person's first name for the lead [optional]
 */
@property(nonatomic) NSString* contactFirstName;
/* The person's last name for the lead [optional]
 */
@property(nonatomic) NSString* contactLastName;
/* Gender for contact name; possible values are Male, Female, and Neutral (can be applied to Male or Female).  Requires ContactFirstName. [optional]
 */
@property(nonatomic) NSString* contactGender;
/* Name of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyName;
/* Domain name / website for the lead [optional]
 */
@property(nonatomic) NSString* companyDomainName;
/* House number of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyHouseNumber;
/* Street name of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyStreet;
/* City of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyCity;
/* State or Province of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyStateOrProvince;
/* Postal Code of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyPostalCode;
/* Country Name of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyCountry;
/* Country Code (2-letter ISO 3166-1) of the address of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyCountryCode;
/* Telephone of the company office for the lead [optional]
 */
@property(nonatomic) NSString* companyTelephone;
/* VAT number of the company for the lead [optional]
 */
@property(nonatomic) NSString* companyVATNumber;
/* Count of employees at the company (estimated), if available [optional]
 */
@property(nonatomic) NSNumber* employeeCount;

@end
