#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMParseAddressResponse
@end

@interface CMParseAddressResponse : CMObject

/* True if the parsing operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* The name of the building, house or structure if applicable, such as \"Cloudmersive Building 2\".  This will often by null. [optional]
 */
@property(nonatomic) NSString* building;
/* The street number or house number of the address.  For example, in the address \"1600 Pennsylvania Avenue NW\" the street number would be \"1600\".  This value will typically be populated for most addresses. [optional]
 */
@property(nonatomic) NSString* streetNumber;
/* The name of the street or road of the address.  For example, in the address \"1600 Pennsylvania Avenue NW\" the street number would be \"Pennsylvania Avenue NW\". [optional]
 */
@property(nonatomic) NSString* street;
/* The city of the address. [optional]
 */
@property(nonatomic) NSString* city;
/* The state or province of the address. [optional]
 */
@property(nonatomic) NSString* stateOrProvince;
/* The postal code or zip code of the address. [optional]
 */
@property(nonatomic) NSString* postalCode;
/* Country of the address, if present in the address.  If not included in the address it will be null. [optional]
 */
@property(nonatomic) NSString* countryFullName;
/* Two-letter ISO 3166-1 country code [optional]
 */
@property(nonatomic) NSString* iSOTwoLetterCode;

@end
