#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPhoneNumberValidationResponse
@end

@interface CMPhoneNumberValidationResponse : CMObject

/* True if the phone number is valid, false otherwise [optional]
 */
@property(nonatomic) NSNumber* isValid;
/* True if the operation was successful, false if there was an error during validation.  See IsValid for validation result. [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Type of phone number; possible values are: FixedLine, Mobile, FixedLineOrMobile, TollFree, PremiumRate,   SharedCost, Voip, PersonalNumber, Pager, Uan, Voicemail, Unknown [optional]
 */
@property(nonatomic) NSString* phoneNumberType;
/* E.164 format of the phone number [optional]
 */
@property(nonatomic) NSString* e164Format;
/* Internaltional format of the phone number [optional]
 */
@property(nonatomic) NSString* internationalFormat;
/* National format of the phone number [optional]
 */
@property(nonatomic) NSString* nationalFormat;
/* Two digit country code of the phone number [optional]
 */
@property(nonatomic) NSString* countryCode;
/* User-friendly long name of the country for the phone number [optional]
 */
@property(nonatomic) NSString* countryName;

@end
