#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPublicHolidayOccurrence
@end

@interface CMPublicHolidayOccurrence : CMObject

/* Name of the holiday in English [optional]
 */
@property(nonatomic) NSString* englishName;
/* Local name of the holiday [optional]
 */
@property(nonatomic) NSString* localName;
/* Date of the holiday (start time) [optional]
 */
@property(nonatomic) NSDate* occurrenceDate;
/* Type of the holiday; possible values are: Public, Bank, School, Authorities, Optional, Observance [optional]
 */
@property(nonatomic) NSString* holidayType;
/* True if the holiday is celebrated in all locales in the country, false otherwise [optional]
 */
@property(nonatomic) NSNumber* nationwaide;

@end
