#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMUserAgentValidateResponse
@end

@interface CMUserAgentValidateResponse : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* True if the request is a known robot, false otherwise [optional]
 */
@property(nonatomic) NSNumber* isBot;
/* Optional; name of the robot if the request was from a known robot, otherwise null [optional]
 */
@property(nonatomic) NSString* botName;
/* Optional; if available, the URL to the robot [optional]
 */
@property(nonatomic) NSString* botURL;
/* Operating System of the User-Agent (e.g. Windows) [optional]
 */
@property(nonatomic) NSString* operatingSystem;
/* The CPU platform of the User-Agent (e.g. x64) [optional]
 */
@property(nonatomic) NSString* operatingSystemCPUPlatform;
/* The version of the operating system of the User-Agent (e.g. \"10\" for Windows 10) [optional]
 */
@property(nonatomic) NSString* operatingSystemVersion;
/* Device type of the User-Agent; possible values are \"DESKTOP\", \"SMARTPHONE\", \"TABLET\" [optional]
 */
@property(nonatomic) NSString* deviceType;
/* Brand name of the User-Agent [optional]
 */
@property(nonatomic) NSString* deviceBrandName;
/* Model name or number of the User-Agent [optional]
 */
@property(nonatomic) NSString* deviceModel;
/* Name of the Browser [optional]
 */
@property(nonatomic) NSString* browserName;
/* Version of the Browser [optional]
 */
@property(nonatomic) NSString* browserVersion;
/* Name of the Browser Engine [optional]
 */
@property(nonatomic) NSString* browserEngineName;
/* Version of the Browser Engine [optional]
 */
@property(nonatomic) NSString* browserEngineVersion;

@end
