#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMValidateAddressResponse
@end

@interface CMValidateAddressResponse : CMObject

/* True if the address is valid, false otherwise [optional]
 */
@property(nonatomic) NSNumber* validAddress;
/* If the address is valid, the degrees latitude of the validated address, null otherwise [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* If the address is valid, the degrees longitude of the validated address, null otherwise [optional]
 */
@property(nonatomic) NSNumber* longitude;

@end
