#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMValidateIdentifierRequest
@end

@interface CMValidateIdentifierRequest : CMObject

/* Text string identifier input [optional]
 */
@property(nonatomic) NSString* input;
/* True if whitespace is allowed in the identifier, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowWhitespace;
/* True if hyphens are allowd in the identifier, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowHyphens;
/* True if underscores are allowed in the identifier, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowUnderscore;
/* True if numbers are allowed in the identifier, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowNumbers;
/* True if periods are allowed in the identifier, false otherwise [optional]
 */
@property(nonatomic) NSNumber* allowPeriods;
/* Optional; maximum length, if any, of the identifier [optional]
 */
@property(nonatomic) NSNumber* maxLength;
/* Optional; minimum length, if any, of the identifier [optional]
 */
@property(nonatomic) NSNumber* minLength;

@end
