#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMValidateCityResponse
@end

@interface CMValidateCityResponse : CMObject

/* True if the city is valid, false otherwise [optional]
 */
@property(nonatomic) NSNumber* validCity;
/* If valid, City corresponding to the input postal code, such as 'Walnut Creek' [optional]
 */
@property(nonatomic) NSString* city;
/* If valid; State or province corresponding to the input state name, such as 'CA' or 'California' [optional]
 */
@property(nonatomic) NSString* stateOrProvince;
/* If the postal code is valid, the degrees latitude of the centroid of the state, null otherwise [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* If the postal code is valid, the degrees longitude of the centroid of the state, null otherwise [optional]
 */
@property(nonatomic) NSNumber* longitude;

@end
