#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMVatLookupResponse
@end

@interface CMVatLookupResponse : CMObject


@property(nonatomic) NSString* countryCode;

@property(nonatomic) NSString* vatNumber;

@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* businessAddress;

@end
