#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMWhoisResponse
@end

@interface CMWhoisResponse : CMObject

/* True if the domain is valid, false if it is not [optional]
 */
@property(nonatomic) NSNumber* validDomain;
/* Name of the domain registrant [optional]
 */
@property(nonatomic) NSString* registrantName;
/* Organization name of the domain registrant [optional]
 */
@property(nonatomic) NSString* registrantOrganization;
/* Email address of the domain registrant [optional]
 */
@property(nonatomic) NSString* registrantEmail;
/* Street number of the address of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantStreetNumber;
/* Street name of the address of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantStreet;
/* City of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantCity;
/* State or Province of the address of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantStateOrProvince;
/* Postal code of the address of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantPostalCode;
/* Country of the address of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantCountry;
/* Raw address string of the domain registrant, if available [optional]
 */
@property(nonatomic) NSString* registrantRawAddress;
/* Telephone number of the address of the domain registrant [optional]
 */
@property(nonatomic) NSString* registrantTelephone;
/* Server used to lookup WHOIS information (may change based on lookup). [optional]
 */
@property(nonatomic) NSString* whoisServer;
/* WHOIS raw text record [optional]
 */
@property(nonatomic) NSString* rawTextRecord;
/* Creation date for the record [optional]
 */
@property(nonatomic) NSDate* createdDt;

@end
