#import <Foundation/Foundation.h>
#import "CMPhoneNumberValidateRequest.h"
#import "CMPhoneNumberValidationResponse.h"
#import "CMApi.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMPhoneNumberApi: NSObject <CMApi>

extern NSString* kCMPhoneNumberApiErrorDomain;
extern NSInteger kCMPhoneNumberApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Validate phone number (basic)
/// Validate a phone number by analyzing the syntax
///
/// @param value Phone number to validate in a PhoneNumberValidateRequest object.  Try a phone number such as \&quot;1.800.463.3339\&quot;, and either leave DefaultCountryCode blank or use \&quot;US\&quot;.
/// 
///  code:200 message:"OK"
///
/// @return CMPhoneNumberValidationResponse*
-(NSURLSessionTask*) phoneNumberSyntaxOnlyWithValue: (CMPhoneNumberValidateRequest*) value
    completionHandler: (void (^)(CMPhoneNumberValidationResponse* output, NSError* error)) handler;



@end
