#import <Foundation/Foundation.h>
#import "CMUserAgentValidateRequest.h"
#import "CMUserAgentValidateResponse.h"
#import "CMApi.h"

/**
* validateapi
* The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMUserAgentApi: NSObject <CMApi>

extern NSString* kCMUserAgentApiErrorDomain;
extern NSInteger kCMUserAgentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Parse an HTTP User-Agent string, identify robots
/// Uses a parsing system and database to parse the User-Agent into its structured component parts, such as Browser, Browser Version, Browser Engine, Operating System, and importantly, Robot identification.
///
/// @param request Input parse request
/// 
///  code:200 message:"OK"
///
/// @return CMUserAgentValidateResponse*
-(NSURLSessionTask*) userAgentParseWithRequest: (CMUserAgentValidateRequest*) request
    completionHandler: (void (^)(CMUserAgentValidateResponse* output, NSError* error)) handler;



@end
